### ISSUE TITLE
How is this linter better (or different) than https://staticcheck.dev/docs/checks/#SA9001 ?

### ISSUE THREAD

**Issue by miparnisari** [gsquire/dll#12]

**Comment by gsquire** [comment]
I didn't know this check was already part of `staticcheck` at the time I wrote this tool. It was mostly educational for me I guess.

**Comment by miparnisari** [comment]
@gsquire that's perfectly ok! Maybe add a line on the readme saying that? Just so others don't use both

**Comment by gsquire** [comment]
Sure, noted [here](https://github.com/gsquire/dll#other-works).

Thanks!

**Comment by RaduBerinde** [comment]
SA9001 is much more specific, it's only for defers inside loops that range on channels. The error it produces is "defers in this range loop won't run unless the channel gets closed".
