### ISSUE TITLE
Still in maintainning?

### ISSUE THREAD

**Issue by CyanCherry** [gsquire/dll#13]
Is this repo stil in maintaining?
This rule is REALLY helpful for my repos, it would be better if I can use this linter with golangci-lint.
I'd like to fork this repo and contribute it to golangci-lint.

**Comment by gsquire** [comment]
Yes, I will still respond to any issues but I think this is fairly stable at the moment.

I will gladly take a PR that allows golangci-lint integration. Otherwise, feel free to fork it as well. See #4 for prior chats about this.
