### ISSUE TITLE
Fails to identify defers in nested BlockStmt

### ISSUE THREAD

**Issue by dennisfischer** [gsquire/dll#2]
Defers in nested `BlockStmt` are not detected.

```go
package main

import (
	"fmt"
)

func main() {
	for i := 0; i < 5; i++ {
		defer fmt.Println("Hello, playground")
		{
			defer fmt.Println("Hello, playground") //Not detected
		}
		fmt.Println(i)
	}
}
```

Bug is in https://github.com/gsquire/dll/blob/adb0f52593d650e8e278f6b59e6ad0db22845ab1/dll.go#L42-L50

Instead of looking into the `BlockStmt` of the for loop all child elements have to be checked. I haven't worked much with `ast` package, but I'd assume that you'd need another walker+visitor here.

**Comment by gsquire** [comment]
Thanks for this, I had totally overlooked those types of statements and expressions initially. I believe there is a better way than trying to account for all nodes that can contain `defer` statements so I will have to take a further look.
